baseURL: https://kappq.github.io
languageCode: en-us
title: Kappa's Blog
theme: PaperMod

params:
  defaultTheme: auto
  showToc: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 30
    - identifier: github
      name: GitHub
      url: https://github.com/kappq
      weight: 40
